mmkreservation/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from mmkreservation import views

app_name = 'mmkreservation'

urlpatterns= [
	
	path('Home', views.Home.as_view(), name="Home_view"),
	path('rates', views.Rates.as_view(), name="rates_view"),
	path('portfolio', views.Portfolio.as_view(), name="portfolio_view"),
	path('signup', views.Signup.as_view(), name="signup_view"),
	path('login', views.Login.as_view(), name="login_view"),
	path('adminpage', views.AdminPage.as_view(), name="admin_view"),
	path('adminrooms', views.AdminRoomsDashboard.as_view(), name="adminroom_view"),
	path('adminpayment', views.AdminPaymentDashboard.as_view(), name="adminpayment_view"),

	path('rooms', views.RoomAdd.as_view(), name="rooms_view"),
	path('rooms/<conferenceId>/', views.RoomAdd.as_view(), name="rooms_view"),
	path('payment', views.PaymentPage.as_view(), name="payment_view"),

##Rooms add from user to admin
	path('adminaccounts', views.AdminAccountsDashboard.as_view(), name="adminaccounts_view"),
	path('success', views.Success.as_view(), name="success_view"),
	
	##Rooms add from admin to user
	path('adminviewroom', views.AdminViewRoom.as_view(), name="adminviewroom_view"),
	##Dashboard
	path('userviewroom', views.UserViewRoom.as_view(), name="userviewroom_view"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mmmkhotel/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mmkreservation.urls')),
]

templates/adminaccounts.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
      <!-- Favicons -->
   
  <link href="{% static 'assets/img/logo1.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
        <title>USER DASHBOARD</title>
      <!-- Bootstrap CSS -->
        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

    <!-- jQuery library -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>

    <!-- Latest compiled JavaScript -->
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <!----css3---->
        <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
    
    
    <!--google fonts -->
  
      <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
  
  
  <!--google material icon-->
      <link href="https://fonts.googleapis.com/css2?family=Material+Icons"rel="stylesheet">

  </head>
  <body>
  

<div class="wrapper">

        <div class="body-overlay"></div>
    
    <!-------------------------sidebar------------>
         <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3><img src="{% static 'assets\img\logo1.png' %}" class="img-fluid"/><span>MMK HOTEL</span></h3>
               {% for accountadmin in accountadmin %}
                <p>{{accountadmin.username}}</p>
                 {% endfor %} 
                
            </div>
            <ul class="list-unstyled components">
                <li>
                              <a href="{% url 'mmkreservation:admin_view' %}" class="dashboard"><i class="material-icons">dashboard</i>
                    <span>HOME</span></a>
                          </li>
              
          
                          <li class="active">
                              <a href="#homeSubmenu1" data-toggle="collapse" aria-expanded="false" 
                    class="dropdown-toggle">
                    <i class="material-icons">aspect_ratio</i>Account</a>
                              <ul class="collapse list-unstyled menu" id="homeSubmenu1">
                                  <li>
                                      <a href="{% url 'mmkreservation:adminaccounts_view' %}">User</a>
                                  </li>
                                  
                                
                              </ul>
                </li>

                <li class="dropdown">
                  <a href="{% url 'mmkreservation:adminroom_view' %}">
                  <i class="material-icons">apps</i><span>Rooms Booked</span></a>
                 
              </li>
      
              <li class="dropdown">
                <a href="{% url 'mmkreservation:adminviewroom_view' %}">
                <i class="material-icons">apps</i><span>Add Rooms</span></a>
               
            </li>
        
        
                <li class="dropdown">
                  <a href="{% url 'mmkreservation:adminpayment_view' %}">
                  <i class="material-icons">apps</i><span>Payments</span></a>
                 
              </li>
              <li class="dropdown" class="active">
                <a href="{% url 'mmkreservation:login_view' %}">
                <i class="material-icons">apps</i><span>Log Out</span></a>
               
            </li>
        </nav>
    
    
    
    
    <!--------page-content---------------->
    
    <div id="content">
       
       <!--top--navbar----design--------->
       
       <div class="top-navbar">
          <div class="xp-topbar">

                <!-- Start XP Row -->
                <div class="row"> 
                    <!-- Start XP Col -->
                    <div class="col-2 col-md-1 col-lg-1 order-2 order-md-1 align-self-center">
                        <div class="xp-menubar">
    
                </a>
                            </li>
              
        
              
                        </div>
                    </div>
                    <!-- End XP Col -->

                </div> 
                <!-- End XP Row -->

            </div>
         <div class="xp-breadcrumbbar text-center">
                <h4 class="page-title">Account</h4>  
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">User</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                  </ol>                
            </div>
      
       </div>
       
       




       
       <!--------main-content------------->
      
       <div class="main-content">
        <div class="row">
          
        <div class="col-md-12">
        <div class="table-wrapper">
    <div class="table-title">
      <div class="row">
        <div class="col-sm-6 p-0 d-flex justify-content-lg-start justify-content-center">
          <h2 class="ml-lg-2">View Users</h2>
        </div>
     
     
      </div>
    </div>
    {% block content %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>
       
          </th>
          <th>Order ID</th> 
          <th>First Name</th> 
          <th>Last Name</th> 
          <th>Email</th> 
          <th>Address</th>
          <th>Age</th>

          <th>Username</th>
          <th>Password</th>
          <th>Action</th> 
        </tr>
      </thead>
      
            {% for user in user %}
            <tr>
                <td>   
                <td>{{user.uid}}</td> 
                <td>{{user.first_name}}</td> 
                <td>{{user.last_name}}</td> 
                <td>{{user.email}}</td> 
                <td>{{user.address}}</td> 
                <td>{{user.age}}</td>

                 <td>{{user.username}}</td>
                 <td>{{user.password}}</td>
                 
                <td>
                  
                
                  
                    <button href="#" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{user.id}}" data-whatever="@mdo data-placement=" title="Update">UPDATE</button>

                    <div class="modal fade" id="exampleModal-{{accounts.uid}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="false"> 
                      <div class="modal-dialog" style="width: 1500px; padding-top: 200px">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Update User</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>                              
                              
                              <div class="modal-body">
                                <form method="POST">
                                  {% csrf_token %}
                                  <div class="form-group">
                                
                                 <label for="recipient-name" class="col-form-label">Order ID</label>
                                <input name="uid-uid" value="{{user.uid}}" subject.type="text" class="form-control" id="uid-uid" readonly>

                                  <label for="recipient-name" class="col-form-label">First Name</label>
                                  <input type="text" name="first-name" value="{{user.first_name}}" class="form-control" id="first-name">
                        
                                  <label for="recipient-name" class="col-form-label">Last Name</label>
                                  <input type="text" name="last-name" value="{{user.last_name}}" class="form-control" id="last-name">
                                  <label for="recipient-name" class="col-form-label">Email</label>
                                  <input type="text" name="email-email" value = "{{user.email}}" class="form-control" >
                        
                                  <label for="recipient-name" class="col-form-label">Address</label>
                                  <input type="text" name="address-address" value="{{user.address}}" class="form-control" id="address-address">

                                  <label for="recipient-name" class="col-form-label">Age</label>
                                  <input type="text" name="age-age" value="{{user.age}}" class="form-control" id-="age-age">

                                  <label for="recipient-name" class="col-form-label">Username</label>
                                   <input type="text" name="user-name" value="{{user.username}}" class="form-control" id=" user-name">
                        
                                  <label for="recipient-name" class="col-form-label">Password</label>
                                  <input type="text" name="pass-word" value="{{user.password}}" class="form-control" id=" pass-word">
                            
                                  </div>
                                
                        
                                
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                                <button type="submit" id="BtnUpdate" name="BtnUpdate" href = "{% url 'mmkreservation:Home_view' %}" class="btn btn-primary">UPDATE</button>
                              </div>

                                </form>
                              </div>
                            </div>
                          </div>
                        </div>
                        
                        
                        <!-- Button trigger modal -->
  <a href="button" href="#" class="btn btn-primary" data-target="#Modal-{{user.uid}}"data-toggle="modal">DELETE</a>
    </div>
                          
                         <!-- Modal HTML -->
<div id="Modal-{{user.uid}}" class="modal fade" data-backdrop="false">
  <div class="modal-dialog modal-confirm">
    <div class="modal-content">
      <div class="modal-header">
        <div class="icon-box">
          <i class="material-icons">&#xE5CD;</i>
        </div>        
        <h4 class="modal-title">Are you sure?</h4>  
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <form method="POST">
          {% csrf_token %}

      <div class="modal-body">
        <input type="text" name="iidn-idn" value = {{user.uid}} hidden>
        Are you sure you want to delete
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
        <button type="submit" id="BtnDelete" name="BtnDelete" class="btn btn-danger">Delete</button>
      </div>
    </div>
  </div>
    {% endfor %}  
</div>  
                </td> 
             </tr>
                      
            </tbody>
            </table>
        </div>
        </div>
    </div>
   

  
    
{% endblock content %}



<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
 
  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="copyright">
            &copy; Copyright <strong>MMK Hotel</strong>. All Rights Reserved
          </div>
          <div class="credits">
            <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Imperial
          -->
            Designed by <a href="https://bootstrapmade.com/">MMK HOTEL</a>
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End Footer --




  
     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="{% static 'assets\js\js\jquery-3.3.1.slim.min.js' %}"></script>
   <script src="{% static 'assets\js\js\popper.min.js' %}"></script>
   <script src="{% static 'assets\js\js\bootstrap.min.js' %}"></script>
   <script src="{% static 'assets\js\js\jquery-3.3.1.min.js' %}"></script>
  
  
  <script type="text/javascript">
        
    $(document).ready(function(){
      $(".xp-menubar").on('click',function(){
        $('#sidebar').toggleClass('active');
      $('#content').toggleClass('active');
      });
      
       $(".xp-menubar,.body-overlay").on('click',function(){
         $('#sidebar,.body-overlay').toggleClass('show-nav');
       });
      
    });
    
</script>
  
  

  </body>
  
  </html>

templates/adminpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="wrapper">
  <div class="body-overlay"></div>
  <!-------------------------sidebar------------>
  <!-- Sidebar  -->
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>
        <img src="{% static 'assets\img\logo1.png' %}" class="img-fluid" />
        <span>MMK HOTEL</span>
      </h3> {% for accountadmin in accountadmin %} <p>{{accountadmin.username}}</p> {% endfor %}
    </div>
    <ul class="list-unstyled components">
      <li class="active">
        <a href="{% url 'mmkreservation:admin_view' %}" class="dashboard">
          <i class="material-icons">dashboard</i>
          <span>HOME</span>
        </a>
      </li>
      <li class="dropdown">
        <a href="#homeSubmenu1" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
          <i class="material-icons">aspect_ratio</i>Account </a>
        <ul class="collapse list-unstyled menu" id="homeSubmenu1">
          <li>
            <a href="{% url 'mmkreservation:adminaccounts_view' %}">User</a>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="{% url 'mmkreservation:adminroom_view' %}">
          <i class="material-icons">apps</i>
          <span>Rooms Booked</span>
        </a>
      </li>
      <li class="dropdown">
        <a href="{% url 'mmkreservation:adminviewroom_view' %}">
          <i class="material-icons">apps</i>
          <span>Add Rooms</span>
        </a>
      </li>
      <li class="dropdown">
        <a href="{% url 'mmkreservation:adminpayment_view' %}">
          <i class="material-icons">apps</i>
          <span>Payment</span>
        </a>
      </li>
      <li class="dropdown">
        <a href="{% url 'mmkreservation:login_view' %}">
          <i class="material-icons">apps</i>
          <span>Log Out</span>
        </a>
      </li>
  </nav>
  <!--------page-content---------------->
  <div id="content">
    <!--top--navbar----design--------->
    <div class="top-navbar">
      <div class="xp-topbar">
        <!-- Start XP Row -->
        <div class="row">
          <!-- Start XP Col -->
          <div class="col-2 col-md-1 col-lg-1 order-2 order-md-1 align-self-center">
            <div class="xp-menubar">
              </a>
              </li>
              <h2 class="ml-lg-2">DASHBOARD</h2>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid p-5">
      <div class="row">
        <div class="col-12">
          <div class="card m-2">
            <div class="card-body">
              <h5 class="card-title"><strong>Total Sales</strong></h5>
              <p class="card-text" style="font-size: 50px;">$ {{ totalSales }} </p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        {% for x in roomBooks %}
        <div class="col-6">
          <div class="card m-2">
            <div class="card-body">
              <h5 class="card-title"><strong>{{ x.conference.roomname }}</strong></h5>
              <h6 class="card-subtitle mb-2 text-muted">{{ x.conference.roomtype }}</h6>
              <p class="card-text">Number of bookings {{ x.count }} </p>
            </div>
          </div>
        </div>
        {% endfor %}  
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">

  $(document).ready(function () {
    $(".xp-menubar").on('click', function () {
      $('#sidebar').toggleClass('active');
      $('#content').toggleClass('active');
    });

    $(".xp-menubar,.body-overlay").on('click', function () {
      $('#sidebar,.body-overlay').toggleClass('show-nav');
    });

  });

</script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>MMK Hotel Reservation</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
      <!-- Favicons -->
   
  <link href="{% static 'assets/img/logo1.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  <!-- Facebook Opengraph integration: https://developers.facebook.com/docs/sharing/opengraph -->
  <meta property="og:title" content="">
  <meta property="og:image" content="">
  <meta property="og:url" content="">
  <meta property="og:site_name" content="">
  <meta property="og:description" content="">

  <!-- Twitter Cards integration: https://dev.twitter.com/cards/  -->
  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="">
  <meta name="twitter:title" content="">
  <meta name="twitter:description" content="">
  <meta name="twitter:image" content="">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png'%}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800" rel="stylesheet">
  <!--google material icon-->
  <link rel="preconnect" href="https://fonts.googleapis.com">
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Icons"rel="stylesheet"> 
  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css'%}'" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css'%}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
  <!-- =======================================================
  * Template Name: Imperial - v5.7.0
  * Template URL: https://bootstrapmade.com/imperial-free-onepage-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>
    {% block content %}
    {% endblock %}

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/aos/aos.js'%}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js'%}"></script>
  <script src="{% static 'assets/vendor/typed.js/typed.min.js'%}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js'%}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js'%}"></script>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
  <script src="{% static 'new/js/vendor/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'new/js/vendor/jquery.sortelements.js' %}" type="text/javascript"></script>
  <script src="{% static 'new/js/jquery.bdt.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'assets\js\js\popper.min.js' %}"></script>
  <script>
      $(document).ready( function () {
          $('#bootstrap-table').bdt({
              showSearchForm: 1,
              showEntriesPerPageField: 1
          });
      });
  </script>
</body>

</html>

templates/login.html
  {% extends 'base.html' %}
  {% load static %}
    {% block content %}
    <header id="header" class="d-flex align-items-center">
      <div class="container d-flex align-items-center justify-content-between">
    
        <a href="index.html" class="logo mr-auto"><img src="{% static 'assets/img/logo1.png'%}" alt=""></a>
        <!-- Uncomment below if you prefer to use a text logo -->
        <!-- <h1 class="logo mr-auto"><a href="index.html">Imperial</a></h1> -->
        <!-- <img src="{% static 'assets\img\conference6.jpg' %}"/> -->
        <nav id="navbar" class="navbar">
          <ul>
            <li><a class="nav-link scrollto active" href="{% url 'mmkreservation:Home_view' %}#hero">Home</a></li>
            <li><a class="nav-link scrollto" href="{% url 'mmkreservation:Home_view' %}#about">About</a></li>
            <li><a class="nav-link scrollto" href="{% url 'mmkreservation:Home_view' %}#services">Services</a></li>
            <li><a class="nav-link scrollto " href="{% url 'mmkreservation:Home_view' %}#portfolio">Portfolio</a></li>
            <li><a class="nav-link scrollto" href="{% url 'mmkreservation:Home_view' %}#testimonials">Reviews</a></li>
            <li><a class="nav-link scrollto" href="{% url 'mmkreservation:Home_view' %}#team">Team</a></li>
            </li>
            <li><a class="nav-link scrollto" href="{% url 'mmkreservation:Home_view' %}#contact">Contact</a></li>
    
            </li>
            <li class="dropdown"><a href="#"><span>Account</span> <i class="bi bi-chevron-down"></i></a>
              <ul>
                <li><a href="{% url 'mmkreservation:login_view' %}">Login</a></li>
                <li><a href="{% url 'mmkreservation:signup_view' %}">Sign Up</a></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>Rooms </span> <i class="bi bi-chevron-down"></i></a>
              <ul>
                <li><a href="{% url 'mmkreservation:userviewroom_view' %}">View Rooms Available</a></li>
                <li>
                  <a href="{% url 'mmkreservation:rates_view' %}" ">Rates</a>
                </li>
                <li>
                  <a href=" {% url 'mmkreservation:payment_view' %} ">Payment</a>
                </li>
              </ul>
              </li>
          </ul>
        </nav>
      </div>
    </header>
    <!-- End Header -->
  <main id=" main ">
      <!-- ======= Breadcrumbs ======= -->
      <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">
          <div class="d-flex justify-content-between align-items-center ">
            <h2>Members</h2>
            <ol>
              <li>
                <a href="Home#hero ">Home</a>
              </li>
              <li>Members</li>
            </ol>
          </div>
        </div>
      </section>
      <!-- End Breadcrumbs -->
      <div class="image" style="background: url( '{% static 'assets/img/hero-bg.jpg'%}')"></div>
      <br>
      <br>
      <br>
      <div class="container">
        <div class="d-flex justify-content-center h-100 ">
          <div class="card ">
            <div class="card-header ">
              <h3>Sign In</h3>
              <div class="d-flex justify-content-end social_icon ">
                <span>
                  <i class="fab fa-facebook-square "></i>
                </span>
                <span>
                  <i class="fab fa-google-plus-square "></i>
                </span>
                <span>
                  <i class="fab fa-twitter-square "></i>
                </span>
              </div>
            </div>
            <div class="card-body ">
              <form method="POST"> {% csrf_token %} <div class="input-group form-group ">
                  <div class="input-group-prepend ">
                    <span class="input-group-text ">
                      <i class="fas fa-user "></i>
                    </span>
                  </div>
                  <input type="text" class="form-control" name="username" placeholder="Username">
                </div>
                <div class="input-group form-group ">
                  <div class="input-group-prepend ">
                    <span class="input-group-text ">
                      <i class="fas fa-key "></i>
                    </span>
                  </div>
                  <input type="password" class="form-control" name="password" placeholder="Password">
                </div>
                <center>
                  <div class="row align-items-center remember ">
                    <br>
                    <br>
                    <center>
                      <input type="checkbox">Remember Me
                    </center>
                    <br>
                  </div>
                  <div class="form-group ">
                    <button class="btn float-right login_btn" type="submit">Login</button>
                  </div>
                </center>
              </form>
            </div>
            <div class="card-footer ">
              <div class="d-flex justify-content-center links "> Don't have an account? <a href="{% url 'mmkreservation:signup_view' %} "> Sign Up</a>
              </div>
              <div class="d-flex justify-content-center ">
                <a href="# ">Forgot your password?</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
    </main>
 <!-- End #main -->
 {% endblock %}